### ISSUE TITLE
Sandglass Star Pattern in Java

### ISSUE THREAD

**Issue by dhruvbhatia1** [AdarshAddee/Hacktoberfest2022_for_Beginers#1]
Would like to add a sandglass pattern in Java. Can this issue be assigned to me as a part of Hacktoberfest.

The number of rows will be defined by the user.

The pattern will look something like this -
<img width="142" alt="image" src="https://user-images.githubusercontent.com/65610188/193074635-75c5e25f-966b-4542-8406-4c530c2a8575.png">

**Comment by AdarshAddee** [comment]
Sure, You are welcomed ☺️

**Comment by dhruvbhatia1** [comment]
Hi @AdarshAddee, could you please clarify why have you closed this issue? I haven't yet made a PR for this issue.

Can you please re-open it and also label it as hacktoberfest?

Thanks.
