### ISSUE TITLE
Cycle detection in undirected graph [Graph][C++] 

### ISSUE THREAD

**Issue by Shiyadh123** [AdarshAddee/Hacktoberfest2022_for_Beginers#15]
I would like to add the program to cycle if present in an undirected graph.
Please assign this task to me @AdarshAddee

**Comment by AdarshAddee** [comment]
I would like to know more about this before assigning this task to you. Kindly explain me, I wanna know about as you know about this you can explain me better than others. I'm waiting for your response!!!
Thank you for your interest.

**Comment by Shiyadh123** [comment]
Sorry for the typo in the above request.
I will be adding a program to detect whether a cycle is present in an undirected graph or not. I will be using the DFS technique and for each node will check if it is already visited and if the particular node is not the parent of the current node, a cycle is present and will return true;
