### ISSUE TITLE
Calculate fibonacci series with classes in C++

### ISSUE THREAD

**Issue by dhruvbhatia1** [AdarshAddee/Hacktoberfest2022_for_Beginers#2]
Would like to make a program to print Fibonacci series with classes using C++.

Kindly assign this issue to me as a part of Hacktoberfest.

**Comment by AdarshAddee** [comment]
Sure, You are welcomed ☺️

**Comment by dhruvbhatia1** [comment]
Hi @AdarshAddee, could you please clarify why have you closed this issue? I haven't yet made a PR for this issue.

Can you please re-open it and also label it as hacktoberfest?

Thanks.
